name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
college = input("Enter your college: ")

print("\n--- Your Details ---")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("College:", college)
